// 백엔드 `app/core/utils/error_code.py`의 ErrorCode와 **1:1**로 맞춘다.
// 한쪽에만 추가하면 분기가 조용히 안 먹으므로 같이 고칠 것.
//
//   import { ERROR_CODE } from "@/types/errorCode";
//   if (err.errorCode === ERROR_CODE.TOO_MANY_REQUESTS) { ... }

export const ERROR_CODE = {
  // 공통
  HTTP_ERROR: "HTTP_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",

  // 인증: 토큰
  ACCESS_TOKEN_MISSING: "ACCESS_TOKEN_MISSING",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
  INVALID_TOKEN_TYPE: "INVALID_TOKEN_TYPE",
  INVALID_AUTH_TYPE: "INVALID_AUTH_TYPE",
  REFRESH_TOKEN_MISSING: "REFRESH_TOKEN_MISSING",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  INVALID_REFRESH_PAYLOAD: "INVALID_REFRESH_PAYLOAD",

  // 인증: 세션
  SESSION_REVOKED: "SESSION_REVOKED",
  SESSION_REUSE_DETECTED: "SESSION_REUSE_DETECTED",
  SESSION_STORE_UNAVAILABLE: "SESSION_STORE_UNAVAILABLE",

  // 계정
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ADMIN_NOT_FOUND: "ADMIN_NOT_FOUND",
  USER_DOES_NOT_EXISTS: "USER_DOES_NOT_EXISTS",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",

  // OAuth
  OAUTH_TOKEN_FAILED: "OAUTH_TOKEN_FAILED",
  OAUTH_TOKEN_MISSING: "OAUTH_TOKEN_MISSING",
  OAUTH_USERINFO_FAILED: "OAUTH_USERINFO_FAILED",
  OAUTH_EMAIL_REQUIRED: "OAUTH_EMAIL_REQUIRED",

  // 외부 호출
  UPSTREAM_UNREACHABLE: "UPSTREAM_UNREACHABLE",
  UPSTREAM_INVALID_RESPONSE: "UPSTREAM_INVALID_RESPONSE",

  // 파일 업로드
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_TYPE_NOT_ALLOWED: "FILE_TYPE_NOT_ALLOWED",
  FILE_REQUIRED: "FILE_REQUIRED",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
